### ISSUE TITLE
Code, code security, and more

### ISSUE THREAD

**Issue by ArkAngeL43** [XFORWORKS/DedSec#5]
looking at the code of this framework i found a few things you might want to change 

```sh
api_key=806e8db910e4a9e8f22415e0506debd0
read -p "$(echo -e $blue$bold[?]$reset Enter Country Code ex TN : $nc)" co
read -p "$(echo -e $blue$bold[?]$reset Enter Phone Number : $nc)" number
curl "http://apilayer.net/api/validate?access_key=$api_key&number=$number&country_code=$co&format=1"
#EOF
```

i do not suggest putting your own API key in there, there are other alternatives where you can turn to websites which will change the idea of having an API key, it makes it safer for you, and the people using the tool as some servers will discard API key's if they are not routinely kept up, paid for, etc 

> suggestion  

```python
sleep(0.1)
```

unless you are sending large amounts of data sleep methods are useless ( for future code )

> Second suggestion 

```python
  target_ip = socket.gethostbyname(target)
# Catch CTRL+C to abort
stop = False
```

all of these should be held at the very top under the arguments, coming from a perl programmer it helps alot when it comes to using private and public class variables ( for future code )

> Third ( so far most important suggestion )

```python
    print("""\033[34m\033[1m ___  ___ ___  ___ ___ ___ 
|   \| __|   \/ __| __/ __|
| |) | _|| |) \__ \ _| (__   \033[90mv1.0.7\033[34m
|___/|___|___/|___/___\___|                                         
\033[0m\033[34m-----------------------------------
\033[31m[\033[1mERROR\033[0m\033[31m]
\033[0m\033[94m\033[1m[!]\033[0m Running only on \033[32m\033[1mPython 2\033[0m
""")

i used to do this alot but dont, if you want to print a banner ( since you repeated it all the same time, just do this 

```python
def open_file(color, filename):
      a_file = open(filename)
      file_contents = a_file.read()
      print(color, file_contents)
```

this was you can turn the banner above and 

```
▒██   ██▒  █████▒▒█████   ██▀███   █     █░ ▒█████   ██▀███   ██ ▄█▀  ██████ 
▒▒ █ █ ▒░▓██   ▒▒██▒  ██▒▓██ ▒ ██▒▓█░ █ ░█░▒██▒  ██▒▓██ ▒ ██▒ ██▄█▒ ▒██    ▒ 
░░  █   ░▒████ ░▒██░  ██▒▓██ ░▄█ ▒▒█░ █ ░█ ▒██░  ██▒▓██ ░▄█ ▒▓███▄░ ░ ▓██▄   
 ░ █ █ ▒ ░▓█▒  ░▒██   ██░▒██▀▀█▄  ░█░ █ ░█ ▒██   ██░▒██▀▀█▄  ▓██ █▄   ▒   ██▒
▒██▒ ▒██▒░▒█░   ░ ████▓▒░░██▓ ▒██▒░░██▒██▓ ░ ████▓▒░░██▓ ▒██▒▒██▒ █▄▒██████▒▒
▒▒ ░ ░▓ ░ ▒ ░   ░ ▒░▒░▒░ ░ ▒▓ ░▒▓░░ ▓░▒ ▒  ░ ▒░▒░▒░ ░ ▒▓ ░▒▓░▒ ▒▒ ▓▒▒ ▒▓▒ ▒ ░
░░   ░▒ ░ ░       ░ ▒ ▒░   ░▒ ░ ▒░  ▒ ░ ░    ░ ▒ ▒░   ░▒ ░ ▒░░ ░▒ ▒░░ ░▒  ░ ░
 ░    ░   ░ ░   ░ ░ ░ ▒    ░░   ░   ░   ░  ░ ░ ░ ▒    ░░   ░ ░ ░░ ░ ░  ░  ░  
 ░    ░             ░ ░     ░         ░        ░ ░     ░     ░  ░         ░ 

|   \| __|   \/ __| __/ __|
| |) | _|| |) \__ \ _| (__   \033[90mv1.0.7\033[34m
|___/|___|___/|___/___\___|                                         
\033[0m\033[34m-----------------------------------
\033[31m[\033[1m Keyboard Interrupt\033[0m\033[31m]
\033[0m\033[94m\033[1m[!]\033[0mExiting 
```

into a file function which will read, and output the contents of the file ( the contents in the filename would be the banner), not only that but if you wanted to you can declare the script name version, the filename, the user and author etc as public variables ( visible to all classes) so when you go to output the banner you can easily format the author data and application data all the definitions like the banners here 

```python
     print("\033[94m|\033[34m=============================\033[94m|\033[95m")
     print("\033[94m|     created by \033[90m\033[1mXforworks\033[0m    \033[94m|\033[95m")
     print("\033[94m|\033[34m=============================\033[94m|\033[95m")
     print("\033[94m|     \033[34m++++++++++++++++++++    \033[94m|\033[94m")
     print("\033[94m|                             |\033[95m")
     print("\033[94m|          (DedSec)           |\033[95m")
     print("\033[94m|           \033[90mv1.0.7\033[94m            |\033[95m")
     print("\033[94m|       _,.                   |\033[95m")
     print("\033[94m|     ,` -.)                  |\033[95m")
     print("\033[94m|    ( _/-\\-._                |\033[95m")
     print("\033[94m|   /,|`--._,-^|            , |\033[95m")
     print("\033[94m|   \_| |`-._/||          / | |\033[95m")
     print("\033[94m|     |  `-, / |         /  / |\033[95m")
     print("\033[94m|     |     || |        /  /  |\033[95m")
     print("\033[94m|      `r-._||/   __   /  /   |\033[95m")
     print("\033[94m|  __,-<_     )`-/  `./  /    |\033[95m")
     print("\033[94m|  \   `---    \   / /  /     |\033[95m")
     print("\033[94m| /   |           |./  /      |\033[95m")
     print("\033[94m||    /           //  /       |\033[95m")
     print("\033[94m| \_/  \         |/  /        |\033[95m")
     print("\033[94m|  |    |   _,^- /  /         |\033[95m")
     print("\033[94m|  |    , ``  (\/  /_         |\033[95m")
     print("\033[94m|   \,.->._    \X-=/^         |\033[95m")
     print("\033[94m|   (  /   `-._//^`           |\033[95m")
     print("\033[94m|    `Y-.____(__}             |\033[95m")
     print("\033[94m|     |     {__)              |\033[95m")
     print("\033[94m|           ()                |\033[95m")
     print("")
```

can be easily called and printed out with those colors, print statements when you use to much if you are not formatting them or using WRITE format identifiers then it becomes a bit- well CPU heavy, like having to much IF statements

> one last final thing 

```python
                                os.system("clear")
```

some systems dont use clear, if people want to use this on other systems not that you will remmeber ( i dont either i just copy and paste from my past programs ) but i use this hex code alot 

```go
var(
   clear_hex  = "\x1b[H\x1b[2J\x1b[3J"
)
```

this is a universal hexadecimal / Unicode which will clear the screen of any operating system out there or possible different file system, most people dont use it which i can see as an issue with other scripts but if you use this by just 

```python
clear_hex  = "\x1b[H\x1b[2J\x1b[3J"
print(clear_hex)
```

and it will auto clear everything, its not like using \r\r\r\\r\r\r\r\\r or \n\n\\n\n\n\n\n\n\\n\n\n\n\\n\n\n\n\n\\\n\n\\\\n\\n\\n\\\ etc....

i know this script was just other peoples mashed together ( for the most part ) like black hydra i saw in there but there are hundreds of ways you can make this better, such as writing to the files, creating banner functions, organizing and laying out the modules and fixing alot of the code that can create security vulnerabilities, if you are reading this and are still here I appreciate your time to come and read this, and certainly hope it helped you out 

~ Kindest regards  | ArkAngeL43 |

**Comment by XFORWORKS** [comment]
@ArkAngeL43

Hello, Ark.
I appreciate the time you took to help out with the the script. I'll make sure to include the suggestion/s on the next DedSec update.

- Retr0 ( XforWorks )
