### ISSUE TITLE
having issue installing repository 

### ISSUE THREAD

**Issue by Crazylover2** [XFORWORKS/DedSec#6]
when running command for python -m pip install -r requirements.txt keeping getting error with this install running kali-linux in terux can please help with issue..

![Screenshot_20220306-055700_Termux.jpg](https://user-images.githubusercontent.com/99925624/156920336-f79385d8-e001-44df-b5ea-b67e038b1a84.jpg)

![Screenshot_20220306-055039_Termux.jpg](https://user-images.githubusercontent.com/99925624/156920343-e1a7beaf-0d97-41d3-a105-309e49d4d22d.jpg)

**Comment by XFORWORKS** [comment]
Hello @Crazylover2 ,
before I continue keep in mind that the Script is only running on python **2.7.X**. Make sure you have that Python Version installed. The Script also runs only on Kali Linux & WSL, so you won't be able to do commands like **apt** or **apt-get**.

The full Setup process file and the DedSec Script itself is only working for Kali Linux & WSL, Termux is not an addition yet but don't worry be patient.

- Retr0 ( XforWorks )

**Comment by Crazylover2** [comment]
> Hello @Crazylover2 ,
> before I continue keep in mind that the Script is only running on python **2.7.X**. Make sure you have that Python Version installed. The Script also runs only on Kali Linux & WSL, so you won't be able to do commands like **apt** or **apt-get**.
> 
> The full Setup process file and the DedSec Script itself is only working for Kali Linux & WSL, Termux is not an addition yet but don't worry be patient.
> 
> - Retr0 ( XforWorks )

thanks buc

**Comment by XFORWORKS** [comment]
Hello again @Crazylover2 ,
I'm so sorry for the misunderstanding.
If you have any further questions, ask.
If not, I'll close the issue.

- Retr0 ( XforWorks )

**Comment by Crazylover2** [comment]
okay so still pretty new to all this,aggravating enough i know,is there any way to manually install that script or do I just need chill an wait,an u good to close issue buc

**Comment by XFORWORKS** [comment]
Hey again @Crazylover2 ,
You can't install it any kind of way yet, but don't worry be patient. The Upcoming-New DedSec version is coming out soon, Termux addition will be added.

- Retr0 ( XforWorks )

**Comment by Crazylover2** [comment]
🤙

**Comment by XFORWORKS** [comment]
See you soon @Crazylover2 ,
I hope We helped you understand a few things about the DedSec Script.

**I'm closing the issue now.**

- Retr0 ( XforWorks )
